language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - composer install

script:
  - phpunit

after_script:
    - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

addons:
    code_climate:
        repo_token: f1107a3842715f563d86ed880f9fbf9c78738ce81d7f5349ede33c8b1e53066d
